"""Added created_at and updated_at timestamp

Revision ID: 89c47063137e
Revises: a5eef85824c7
Create Date: 2025-05-05 19:53:48.158947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c47063137e'
down_revision: Union[str, None] = 'a5eef85824c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('group_members', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('group_members', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('message_attachments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('message_attachments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('messages', 'updated_at')
    op.drop_column('message_attachments', 'updated_at')
    op.drop_column('message_attachments', 'created_at')
    op.drop_column('groups', 'updated_at')
    op.drop_column('group_members', 'updated_at')
    op.drop_column('group_members', 'created_at')
    op.drop_column('friend_requests', 'updated_at')
    # ### end Alembic commands ###
